name: CMake Build

on:
  push:
    branches: [ "dev" ]

jobs:
  build:
    name: "Build ${{ matrix.build_type }}"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]

    steps:

    - uses: actions/checkout@v4

    - name: Update build tools
      shell: bash
      run: |
        sudo apt-get install -y build-essential autoconf libtool pkg-config cmake git

    - name: Install gRPC
      uses: eWaterCycle/setup-grpc@v5
      with:
        grpc-version: 1.62.0

    - name: Setup variables
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: >
        cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} 
        -B ${{ steps.strings.outputs.build-output-dir }}
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

